openapi: 3.1.0
info:
  title: Django сервис друзей
  description: |-
    Проектирование сервиса "друзей".
    Сервис должен предоставлять возможности:
      1) Зарегистрировать нового пользователя.
      2) Отправить пользователю заявку в друзья
      3) Принять/отклонить заявку в друзья от другого пользователя
      4) Посмотреть список своих исходящих и входящих заявок в друзья
      5) Посмотреть список своих друзей
      6) Получить статус дружбы с другим пользователем (нет ничего/есть исходящая заявка/есть входящая заявка/уже друзья)
      7) Удалить из друзей
      8) Если пользователь 1 отправляет заявку пользователю 2, а пользователь 2 отправляет заявку пользователю 1 они автоматически становятся друзьями
  version: 0.0.1
servers:
  - url: https://localhost:8080/api/v1
paths:
  /register:
    post:
      summary: Регистрация нового пользователя
      operationId: createUser
      tags:
        - user_registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistrationRequest'
      responses:
        '201':
          description: Успешная регистрация нового пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default: 
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /friend-requests/{to_user_id}:
    post:
      summary: Отправка заявки в друзья
      description: Отправляет заявку в друзья от текущего пользователя к другому пользователю
      operationId: FriendRequest
      parameters:
        - name: to_user_id
          in: path
          description: id пользователя, которому отправляется заявка
          required: true
          schema:
            type: integer
      tags:
        - friend_requests
      responses:
        '200':
          description: Заявка в друзья успешно отправлена
          content:
            application/json:
              schema:
                type: object
                properties:
                  request_id:
                    type: integer
                    description: Идентификатор заявки в друзья
                  from_user_id:
                    type: integer
                    description: Идентификатор отправителя заявки в друзья
                  to_user_id:
                    type: integer
                    description: Идентификатор получателя заявки в друзья
                  status:
                    type: string
                    description: Статус заявки в друзья (pending)
        '400':
          description: Некорректный запрос
  /friend_requests/{request_id}/accept:
    put:
      summary: Принять заявку в друзья
      operationId: acceptFriendRequest
      tags:
        - friend_requests
      parameters:
        - name: request_id
          in: path
          description: id заявки в друзья
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Заявка в друзья принята
          content:
            application/json:
              schema:
                type: object
                properties:
                  request_id:
                    type: integer
                    description: Идентификатор заявки в друзья
                  from_user_id:
                    type: integer
                    description: Идентификатор отправителя заявки в друзья
                  to_user_id:
                    type: integer
                    description: Идентификатор получателя заявки в друзья
                  status:
                    type: string
                    description: Статус заявки в друзья (accepted)
  /friend_requests/{request_id}/reject:
    put:
      summary: Отклонить заявку в друзья
      operationId: rejectFriendRequest
      tags:
        - friend_requests
      parameters:
        - name: request_id
          in: path
          description: id заявки в друзья
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Заявка в друзья отклонена
          content:
            application/json:
              schema:
                type: object
                properties:
                  request_id:
                    type: integer
                    description: Идентификатор заявки в друзья
                  from_user_id:
                    type: integer
                    description: Идентификатор отправителя заявки в друзья
                  to_user_id:
                    type: integer
                    description: Идентификатор получателя заявки в друзья
                  status:
                    type: string
                    description: Статус заявки в друзья (reject)

components:
  schemas:
    UserRegistrationRequest:
      type: object
      properties:
        username:
          type: string
          description: username
      required:
        - username
    User:
      type: object
      properties:
        id:
          type: integer
          description: id of current user
        username:
          type: string
          description: username of the user
    Error:
      type: object
      properties: 
        code:
          type: integer
        message:
          type: string
      required: 
        - code
        - message
    FriendRequest:
      type: object
      properties:
        request_id:
          type: integer
          description: Идентификатор заявки в друзья
        from_user_id:
          type: integer
          description: Идентификатор отправителя заявки в друзья
        to_user_id:
          type: integer
          description: Идентификатор получателя заявки в друзья
        status:
          type: string
          enum: [pending, accept, reject]
          description: Статус заявки в друзья